name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: eddie89/LeetCode@v2
      with:
        github-token: ${{ tokens.PAT }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
