name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: actions/checkout@v2
      with:
        github-token: 0624ae9dade1dd0833a783258a80dd922e00cc37
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
